{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbyte-aks.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airbyte-aks.labels" . | nindent 4 }}
    component: monitoring
  {{- if .Values.monitoring.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  selector:
    {{- include "airbyte-aks.selectorLabels" . | nindent 4 }}
    component: metrics
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbyte-aks.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airbyte-aks.labels" . | nindent 4 }}
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "airbyte-aks.selectorLabels" . | nindent 6 }}
      component: monitoring
  template:
    metadata:
      labels:
        {{- include "airbyte-aks.selectorLabels" . | nindent 8 }}
        component: monitoring
    spec:
      {{- if .Values.security.serviceAccount.create }}
      serviceAccountName: {{ include "airbyte-aks.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.aks.nodeSelector }}
      nodeSelector:
        {{- include "airbyte-aks.nodeSelector" . | nindent 8 }}
      {{- end }}
      containers:
      - name: prometheus
        image: prom/prometheus:v2.40.0
        ports:
        - containerPort: 9090
          name: metrics
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus/
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ include "airbyte-aks.fullname" . }}-monitoring-config
      - name: prometheus-storage
        emptyDir: {}
---
{{- end }}
{{- end }}
