{{- if .Values.security.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "airbyte-aks.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airbyte-aks.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "airbyte-aks.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  # Allow inter-pod communication within namespace
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS traffic (for external APIs, connectors, etc.)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP traffic
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow database connection (PostgreSQL)
  - to: []
    ports:
    - protocol: TCP
      port: 5432
  # Allow inter-pod communication
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end }}
