{{- if .Values.security.podSecurityStandards.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "airbyte-aks.fullname" . }}-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airbyte-aks.labels" . | nindent 4 }}
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "airbyte-aks.fullname" . }}-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airbyte-aks.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
{{- end }}
